### ISSUE TITLE
crazy idea, wicked elements everywhere

### ISSUE THREAD

**Issue by AndyOGo** [WebReflection/wicked-elements#14]
First great idea, you just eliminated all frustrating custom element glitches 🚀 
I call you Mr. Genius from now.

I'm convinced that this should be wide spread and a pendant project like https://custom-elements-everywhere.com/ would be awesome.

https://wicked-elements-everywhere.com/ 👍 

What do you think?

**Comment by WebReflection** [comment]
I think I don't have time for that, as I'm a full time employee with dozen active projects to maintain already 😅

But yeah, if I had a team of enthusiast people around my projects, it'd be awesome if they could help spreading the word about my stuff 😉

**Comment by AndyOGo** [comment]
I understand.
I will check if it could be forked and adapted
