### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vegarringdal** [WebReflection/wicked-elements#24]
Hi

Been looking at wicket-elements and lighterhtml.
Whats the best way to use wicket-elements and lighthtml together?

I havent had time to test much yet due to limited time last weeks, so figure I could get your view on it first before I start trying and failing 😄 
Please tell me if Ive been thinking all wrong and just using lighterHtml-plus would do pretty much the same and combining these 2.

Hope you get time to give me some tips.
And thanks for making these awsome libs, will be fun to try out more 👍

**Comment by WebReflection** [comment]
Hi, and sorry for late reply.

wicked-elements works best with classic Web flow, where you upgrade on demand whatever lands on the page.

how stuff lands on the page could be defined by the server, or even by the client (React, Vue, lighterhtml, it doesn't matter, really).

however, lighterhtml gices you the ability to simplify wicked elements content.

```js
wickedElements.define('div.gallery', {
  onconnected() {
    fetch('list-of-images.json').then(b => b.json()).then(images => {
      this.images = images;
      this.render();
    });
  }
  renderr() {
    render(this.el, () => html`${this.images.map(img => html`<img src=${img}>`)}`);
  }
});
```

Above is quite a silly example of how you could create a gallery from just an element.

The lighterhtml-plus version would simply give you the ability to define internal elements life cycles, but you could also do that via `wickedElements.define('div.gallery img')`, as example, so it's a matter of taste/requirements/simplification for what you are trying to build.

I hope this answered at least a bit 👋

**Comment by vegarringdal** [comment]
Thank you. 👍
