### ISSUE TITLE
Pass function to define()

### ISSUE THREAD

**Issue by basham** [WebReflection/wicked-elements#26]
Wicked Elements allows you to define an element via an object literal or a class. However, sometimes both of these feel a bit weighty, or it forces you to organize code in a way that is less functional in nature. For example, [React Hooks demonstrates how appealing it is to organize code by concerns, rather than by lifecycle methods](https://twitter.com/andychilton/status/1057089468769828864). This could be done if the following syntax was supported. This provides just two simple lifecycle methods: when the element was added to the DOM and when it was removed from the DOM.

```js
wickedElements.define(selector, function (element) {
  // Initialize
  return function () {
    // Removed
  }
})
```

Most other features that Wicked Elements provides can be done manually with listeners if desired.

In the meantime, a function wrapper like the following (note, the code is untested) could provide a similar API.

```js
function whenAdded (selector, callback) {
  wickedElements.define(selector, {
    init: function (event) {
      const returnedValue = callback(event.currentTarget)
      this.removedCallback = typeof returnedValue === 'function'
        ? returnedValue
        : () => {}
    },
    ondisconnected: function () {
      this.removedCallback()
    }
  })
}
```

This change would help make the API closer to a similar library, [`when-elements`](https://github.com/indiana-university/when-elements).

**Comment by WebReflection** [comment]
How would I distinguish between a class and a function?

**Comment by basham** [comment]
Using `.toString` seems to be a way to distinguish a class from a function.
https://zaiste.net/javascript_is_it_a_class_or_a_function/

```js
function isClass(func) {
  return typeof func === 'function'
    && /^class\s/.test(Function.prototype.toString.call(func));
}

class Human {}
isClass(Human) // true

function speak() {}
isClass(speak) // false
```

**Comment by WebReflection** [comment]
Transpilers are a thing though

**Comment by WebReflection** [comment]
After few thoughts on this, I think using a function that init the element and destroys it once the element won't match anymore the selector is against the purpose of this library, which is to mimic as close as possible custom elements definition and lifecycle.

Accordingly, I think it is OK for people to have a choice and use `when-elements` instead,so that even if the libraries will be similar underneath, the ergonomics/semantics will be purposely different, providing a wider choice to users.

I hope that's OK 👋

**Comment by basham** [comment]
> Dom nodes cannot change tag name, neither `is` attribute, once upgraded, so I'm not sure it's a valid example.

Perhaps the example I gave wasn't the best, as it relied on the `is` attribute. This new example is quite contrived, but imagine something like this. It upgrades the same element in two different ways. One, it makes the button behave like a disclosure. Two, it adds a custom tooltip to the button.

```js
wickedElements.define('[aria-expanded]',
  // Clicking the element will
  // toggle the aria-expanded attribute and
  // toggle the visibility of the element referenced by data-expands.
)
wickedElements.define('[data-tooltip]',
  // Reveal a custom tooltip upon hover or focus.
  // Remove the tooltip if the element no longer has the attribute.
)

html`
  <button
    aria-expanded="false"
    data-expands="answer-1"
    data-tooltip="Ask me the questions, Bridgekeeper. I am not afraid.">
    What is your favorite color?
  </button>
  <div id="answer-1">
    Sir Galahad: Blue. No yellOOOOOOW!
  </div>
`
```

> Both connected and disconnected work exactly like custom elements, so it looks like you want an attribute changed in the middle, but you're after a "destructor", which is weird cause that also means "init" might be invoked twice for the same element, and the same definition.

Yes, I could see it being odd for the case of `wickedElements`, if the presence of `[data-tooltip]` triggered `init()`, then the attribute was removed and added again, causing `init()` to be triggered again. Some different semantics would be needed for that to feel okay.

Nevertheless, if the primary purpose of `onconnected()`, `init()`, or `whenAdded()` is to upgrade an element, I'm struggling with finding compelling reasons to support a method for downgrading the element (by knowing when the element no longer matches the original selector and somehow undoing its setup). It's far easier to just destroy the element, do some clean up, and replace it with something new. And as you suggest, downgrading may just lead to the developer shooting themselves in the foot. I will likely remove this feature from `when-elements`, and that will happily simplify the [`whenRemoved()` API](https://github.com/indiana-university/when-elements#whenremoved). However, I could also see allowing the developer to register a custom when*-like callback, so they could integrate their own hooks into the system as needed. This expansion-ability is hinted at in the [backlog](https://github.com/indiana-university/when-elements#backlog).

Yes, I understand wanting to keep in symmetry with CustomElementsRegistry, and `when-elements` is purposely different from that that API. I'm glad we could clarify the goals of our respective projects.

**Comment by basham** [comment]
Yes, I understand wanting to keep in symmetry with CustomElementsRegistry, and `when-elements` is purposely different than that API. I'm glad we could clarify the goals of our respective projects.

And if I want an API similar to `whenAdded()` but backed by `wickedElements`, it's easy to just use a one-off wrapper or utility like I suggested above.
