### ISSUE TITLE
TypeScript import does not work

### ISSUE THREAD

**Issue by Inpassor** [WebReflection/wicked-elements#33]
Hi!

`import { get, define } from 'wicked-elements';`

says "Module 'wicked-elements' has no exported members 'get', 'define'".

**Comment by WebReflection** [comment]
what am I missing?
https://github.com/WebReflection/wicked-elements/blob/master/index.d.ts#L49-L73

**Comment by Inpassor** [comment]
I believe the last line should be changed to:
`export = wickedElements;`

But I got the next error:

I'm trying to define a custom element as follows:
`define('custom-element', class extends HTMLElement {...})`

> TS2560: Value of type 'typeof (Anonymous class)' has no properties in common with type 'IWickedElementsComponent'. Did you mean to call it?

What is the right syntax to define?

**Comment by WebReflection** [comment]
So, the current definition I've just pushed (1.0.3) explicitly does this:

```js
export const define = wickedElements.define;
export const get = wickedElements.get;
export const upgrade = wickedElements.upgrade;
export const whenDefined = wickedElements.whenDefined;
```

but as I've no idea about TS, since I don't even use it, I'm not sure that's enough.

Regarding the definition, forget about classes, it's just a literal object, as explained in the README, and it boils down to:

```js
wickedElements.define(AnyCSSSelector, {
  init() { this.element; },
  connected() {},
  disconnected() {},
  attributeChanged(name, value, oldValue) {},
  observedAttributes: [...],
  onEventName(event) {},
  onEventNameOptions: {once: true}
});
```

**Comment by WebReflection** [comment]
Btw, latest changes seem to work properly, I have all hints and no issue is shown.

**Comment by WebReflection** [comment]
P.S. I'll try `export = wickedElements;` and see if that's any better.

**Comment by Inpassor** [comment]
Now import works as expected.
I've replaced customElements with your library and it seems to work much better.
Thank you!

**Comment by WebReflection** [comment]
Watch out this library is not a drop-in replacement for `customElements`, most important:

  * the `this` context here is the _behavior_, not the element itself. The element is reachable via `this.element`
  * all mechanisms are based on `MutationObserver` and weak referenced _ behaviors_ (multiple too) per each element, this is a procedural mechanism, not something provided natively by the browser

However, if you get these points, and you want to forget about Custom Elements polyfills, I think you go pretty far with this library 😉

**Comment by Inpassor** [comment]
I see, but I think it fits all my needs.

For now, I got something like this:

```typescript
import { get, define } from 'wicked-elements';

import { getClassData } from '../../server/functions/hosting/helpers';
import { Component } from '../../server/functions/hosting/interfaces';
import { applyGettersAndSetters } from './apply-getters-and-setters';
import { partials } from '../../server/functions/hosting/partials';

export const renderComponent = (instance: Component, tagName: string): void => {
    const eventName = `${tagName}-onDataChange`;
    const render = function(): void {
        const templatePath = instance.__dirname.replace(/\\/g, '/').replace('src/', '');
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const template = require(`../../${templatePath}/${instance.template}.ejs`);
        this.element.innerHTML = template(getClassData(instance));
    };

    if (!get(tagName)) {
        define(tagName, {
            connected() {
                applyGettersAndSetters(instance, eventName);
                render.call(this);
                document.addEventListener(eventName, render.bind(this), false);
                for (const partialName in partials) {
                    const partialTag = `<${partialName}></${partialName}>`;
                    if (partials.hasOwnProperty(partialName) && this.element.innerHTML.indexOf(partialTag) !== -1) {
                        const view: Component = new partials[partialName]();
                        renderComponent(view, partialName);
                    }
                }
            },
            disconnected() {
                document.removeEventListener(eventName, render.bind(this));
            },
        });
    }
};
```

**Comment by WebReflection** [comment]
watch out:

```js
document.removeEventListener(eventName, render.bind(this));
```

this will never work, as `fn.bind(anything)` never produces the same function.

I'd personally use the `init` here, as it's granted to run only once, but always before any `connected`:

```js
init() {
  this.render = render.bind(this);
},
connected() {
  document.addEventListener(eventName, this.render);
},
disconnected() {
  document.removeEventListener(eventName, this.render);
}
```

**Comment by Inpassor** [comment]
Thanks for clarifying. It was very useful.
However, it was working somehow without these changes.
You see, I'm still testing the code.

**Comment by WebReflection** [comment]
> However, it was working somehow without these changes.

It works only because you trash every time everything due usage of `innerHTML`, and the DOM automatically remove listeners from nodes that are not referenced, existing anymore.

It was working by side effect, not by design. Never **ever** use `.bind(...)` directly to add listeners that you want to remove later on, 'cause you won't be able to do so, but also never need to add all listeners and drop them on connect/disconnect, if nodes are either connected only once in their life, or trashed each time due `innerHTML`.
