### ISSUE TITLE
How to include it in the project?

### ISSUE THREAD

**Issue by MikeVaz** [WebReflection/wicked-elements#4]
I looks like you haven't included a guide how to include it in the project in the readme which might scare users from adopting it. Well I can figure it myself. 

What would be nice to have is something like this.

``` npm install wicked-elements --save```
```html
<script type="module"> 
import {?} from "./node_modules/wicked-elements/??/?.js"
</script>
```

Do you have an example of ES6 module usage?

**Comment by WebReflection** [comment]
Is `import wickedElements from 'wicked-elements'` too difficult to use?

**Comment by MikeVaz** [comment]
Well I had like an hour to give it a try. Sorry I couldn't spend more time on weekends to play with it. And it wasn't straight forward as I would expect. First of all I had to guess if you have an `npm` package for that or not and how it is named. After that I was guessing which file from the package is wrapped as ES module.

```import wickedElements from "wicked-elements"```

Would this work inside a `<script>` tag in browser? I guess it is for a nodejs script since you need to resolve "wicked-elements".

Give me some time to play with it so I can accumulate all suggestions and share with you. I can help with WIKI page too. 

For now I can see there could be a problem if you want to inherit from a wicked component or use composition to mix it with other features. These are fundamentally important for me to build UI features.

**Comment by WebReflection** [comment]
I've put an explicit how to:
https://github.com/WebReflection/wicked-elements#how-to

but that's how everything I produce since ever works ... but good point it could've ben explicit.

> Would this work inside a <script> tag in browser?

yes.

> For now I can see there could be a problem if you want to inherit from a wicked component

No, you can use classes too, and inherit whatever you want.

> or use composition to mix it with other features.

the paradigm here is slightly different, you define components by selectors.

An element can be matched by multiple selectors, hence have multiple behaviors.

You've never dialed with this level of composition, considering any behavior could be a mixin, an object, a class, through inheritance or not, so the composition level is the best you could ever have in JS + DOM world, so that if composition is fundamental, you have a whole new world of possibilities here.

**Comment by MikeVaz** [comment]
Just FYI this fails in Chrome

```javascript
import wickedElements from 'wicked-elements'
```

Uncaught TypeError: Failed to resolve module specifier "wicked-elements". Relative references must start with either "/", "./", or "../".

As I suspected above it won't be able to resolve the path.

**Comment by grommett** [comment]
@MikeVaz why don't you just include the `min.js` file if this is for the browser and you don't want to use the CDN option included in the how-to? I have this working pretty nicely in a current project.

There are a few options to use this library as is:

**Out of the box**
```html
<script src="./node_modules/wicked-elements/min.js"></script>
<script> 
  wickedElements.define('[is=app]', {
    init(event) {
     this.el = event.target;
    }
  });
</script>
```

**Build Step**
In your build step you can copy it to your build folder: `cp ./node_modules/wicked-elements/min.js ./build/js`.
Then in the browser and or other files use `wickedElements` as a global:
```html
<script src="min.js"></script>
<script> 
  wickedElements.define('[is=app]', {
    init(event) {
     this.el = event.target;
    }
  });
</script>
```
Or in a file **making sure** `min.js` file is loaded first:
File: `index.html`
```html
<!-- From node_modules -->
<script src="./node_modules/wicked-elements/min.js"></script> 
<!-- OR from build step -->
<script src="min.js"></script>
<script type="module">
  import myApp from "./my-app.js";
</script>
```
File `my-app.js`:
```javascript
  wickedElements.define('[is=app]', {
    init(event) {
     this.el = event.target;
    }
  });
```

**Comment by WebReflection** [comment]
@MikeVaz honestly a bit confused by your answer ...if you use ES modules you need qualified urls as in

`import we from 'https://unpkg.com/wicked-elements'`

My example is for bundlers but of course you can import from a file too

**Comment by MikeVaz** [comment]
@grommett Consider a case when you build a re-usable component like

myComponent.js (ESM)
```javascript
import wickerElement from '...';
import otherDependecies from 'other places';

var myComponent = {};

export default myComponent;
```
Now in your application you can include it as ESM 

```html
<script type="module" src="myComponent.js"></script>
<!-- or -->
<script type="module">
  import myComponent from "./myComponent.js"
</script>
```
@WebReflection your example doesn't work. Please try. 
```javascript
<script type="module">
  import we from 'https://unpkg.com/wicked-elements';
  alert(we);  
</script>
```
https://codepen.io/anon/pen/aPdZJa

Also I can switch to emails if you want to here more feedback or I can continue open cases. Trying to be helpful and support your efforts.

**Comment by WebReflection** [comment]
Sorry, it's 

`import we from 'https://unpkg.com/wicked-elements?module'`

Or you use a bundler.

As summary, this module works already with ESM, and it's developed through ESM, so there's nothing to do here.
