### ISSUE TITLE
error duplicated: .selector

### ISSUE THREAD

**Issue by nuxodin** [WebReflection/wicked-elements#49]
Hi Andrea

Is there a technical reason, why multiple wickedElement instances cannot be added with the same selector?
https://github.com/WebReflection/wicked-elements/blob/336db5dc669620914f331d64436637f6253eee00/esm/index.js#L64

I could imagine that someone wants to enhance a foreign element:

```js
wickedElements.define(
    '.foreignElement', {
        init() {
            this.element.style.background = 'red';
	},
    }
);
```

I can also achieve this by adding a space to the selector.

**Comment by WebReflection** [comment]
You cannot have 2 definitions for the same custom element, so the behavior here simply replicates that limitation that I believe has a reason to exist (no races between definitions).

You can circumvent this as you like though, but being responsible of possible shootguns with same selectors is not likely something wickedElements should have.

Imagine same class has a definition that when live it gets removed and another definition that when removed it gets re-appended ... now, that could happen with two different selectors that target same node, but making this simpler to happen makes little sense.

Are you the owner of the initial definition? Improve that. Are you just using too generic selectors? change that, or mess happens.
