### ISSUE TITLE
How to use children?

### ISSUE THREAD

**Issue by kethan** [WebReflection/wicked-elements#51]
How to use children in this?

**Comment by WebReflection** [comment]
```js
this.element.children
```
???

**Comment by kethan** [comment]
> ```js
> this.element.children
> ```
> 
> ???

I mean children like similar to props and children in React. Having some other tag or elements nested. how to access children in element definition? or do we support slot?

for example 

```<my-counter> ... children </my-counter>```

An example : https://codesandbox.io/s/async-cdn-xr119?file=/src/index.js

**Comment by WebReflection** [comment]
```js
import {render, html} from 'uhtml';
import {define} from 'wicked-elements';

define('x-hello', {
  init() {
    render(this.element, html`Hello ${[...this.childNodes]}`);
  }
});
```

or something similar ... this is the closest thing you can use to enrich the DOM, if you need anything else that is React like, I suggest [uland](https://github.com/WebReflection/uland#readme) or similar projects.

**Comment by kethan** [comment]
Super thank you it worked. uland I saw but it doesn't provide the custom-element feature. 

Edit: Seems working.
https://codepen.io/kethan-the-selector/pen/PomRvrj?editors=1010

I have another question do you have a feature to convert attributes to primitive value or vice versa for example : 
https://github.com/luwes/swiss#syntax

```js
 props: {
    // shorthand property definition w/ default value 0
    count: 0, 

    // readonly getter w/ default value of Steve
    firstName: {
      get: (el, val = 'Steve') => val,
    },

    // getter & setter w/ default value of King
    lastName: {
      get: (el, val = 'King') => val,
      set: (host, value) => value,
    }, 

    // getter that reflects its value to the name attribute
    name: {
      get: ({ firstName, lastName }) => `${firstName} ${lastName}`,
      reflect: true,
    },

    // prop config w/ custom to/from attribute converters
    wheel: {
      get: (host, val = { hub: 1, spokes: [9, 8, 7] }) => val,
      set: (host, val) => val,
      toAttribute: JSON.stringify,
      fromAttribute: JSON.parse,
      reflect: true,
    }
  }
```

This will be very useful.

**Comment by WebReflection** [comment]
for props, and more custom elements like features, you can have a look at [uce](https://github.com/WebReflection/uce#readme), or see if [uce-helpers](https://github.com/WebReflection/uce-helpers#readme) has anything interesting.

Alternatively, you can check [reactive-props](https://github.com/WebReflection/reactive-props#readme) too, which has all demos you want around these libraries.

**Comment by kethan** [comment]
wow, what a nice library I don't understand why so few stars. All in 1.3kb gz. I am mad.

**Comment by WebReflection** [comment]
> what a nice library I don't understand why so few stars

story of my life, I'm used to it ... I have [libraries in npm with 77 million downloads per month](https://www.npmjs.com/package/flatted) and like 700 stars on github ... GitHub stars as metric is overly-estimated since about ever, imho 🤷‍♂️

**Comment by kethan** [comment]
> > what a nice library I don't understand why so few stars
> 
> story of my life, I'm used to it ... I have [libraries in npm with 77 million downloads per month](https://www.npmjs.com/package/flatted) and like 700 stars on github ... GitHub stars as metric is overly-estimated since about ever, imho 🤷‍♂️

oh wow, this is amazing you have written so many libraries which are making my head spin. how do you find such time and that too free? It's so inspiring the work you do. Thank you so much.
