### ISSUE TITLE
IE11 fails to support wicked elements created via document.createElement

### ISSUE THREAD

**Issue by MikeVaz** [WebReflection/wicked-elements#7]
Consider an example
```html
	<script>
		var myComponent = {
			init: function (event) {
				this.el = event.currentTarget;
				this.render();
			},
			render: function() {
				this.el.innerHTML = '<p>I am here</p>';
			}	
		}

		wickedElements.define('div[is="my-component"]', myComponent);

		var el = document.createElement('div', 'my-component');
		document.body.appendChild(el); // Fails in IE11 but works in Chrome
	</script>
	<div is="my-component"></div> <!-- Works in both -->
```

I am trying this case because I wanted to check the sequence of lifecycle events and if it is consistent in all browsers with different ways of creating elements. I found this to be a weak spot of such libraries.

**Comment by MikeVaz** [comment]
But if you add this before appending it would work.
```javascript
el.setAttribute('is', 'my-component');
```
It is a bit weird since you need to distinct `this` from `this.el` now. Compared to what we used in custom elements. 

It reminds me of JQuery plugins.

**Comment by WebReflection** [comment]
IE doesn't support second argument in createElement so this has nothing to do with wicked elements. You can also use any selector, not just `is`.
Lifecycle is tested already in IE 11 and consistent cause it's granted by MutationObserver
